-- DON DUONG VILLAGE - Supabase setup
-- Chạy trong SQL Editor. Không cần service_role key trên website.

-- 1) Bổ sung cột cho bảng product hiện có
alter table public.product add column if not exists is_featured boolean default false;
alter table public.product add column if not exists slug text;
alter table public.product add column if not exists updated_at timestamptz default now();

-- 2) Nội dung website động
create table if not exists public.page_sections (
  id bigint generated by default as identity primary key,
  section_key text unique not null,
  title text,
  subtitle text,
  body text,
  image_url text,
  button_text text,
  button_url text,
  is_active boolean default true,
  sort_order integer default 0,
  updated_at timestamptz default now()
);

create table if not exists public.site_settings (
  id integer primary key default 1 check (id=1),
  brand_name text default 'DON DUONG VILLAGE',
  phone text,
  email text,
  address text,
  facebook_url text,
  tiktok_url text,
  shopee_url text,
  zalo_url text,
  support_hours text default '8:00 - 20:00',
  updated_at timestamptz default now()
);

insert into public.site_settings(id,brand_name) values(1,'DON DUONG VILLAGE')
on conflict (id) do nothing;

-- 3) Blog
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  title text not null,
  slug text unique not null,
  excerpt text,
  cover_url text,
  content_html text,
  status text default 'draft' check (status in ('draft','published')),
  published_at timestamptz
);


-- 3A) Nội dung trang Về chúng tôi (CRUD từ Admin)
create table if not exists public.about_blocks (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  block_type text not null default 'content'
    check (block_type in ('story','mission','vision','value','content')),
  title text not null,
  body text,
  image_url text,
  sort_order integer default 0,
  is_active boolean default true
);

-- 4) Đơn hàng + dòng sản phẩm
create table if not exists public.web_orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  customer_name text not null,
  phone text not null,
  email text,
  address text not null,
  note text,
  subtotal numeric default 0,
  shipping_fee numeric default 0,
  total numeric default 0,
  status text default 'new',
  payment_status text default 'unpaid'
);

create table if not exists public.web_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.web_orders(id) on delete cascade,
  product_id bigint,
  product_name text not null,
  quantity integer not null check(quantity > 0),
  unit_price numeric not null,
  line_total numeric not null
);

-- 5) RLS
alter table public.product enable row level security;
alter table public.page_sections enable row level security;
alter table public.site_settings enable row level security;
alter table public.posts enable row level security;
alter table public.about_blocks enable row level security;
alter table public.web_orders enable row level security;
alter table public.web_order_items enable row level security;

-- Xóa policy cùng tên nếu chạy lại
drop policy if exists "public read product" on public.product;
drop policy if exists "auth manage product" on public.product;
drop policy if exists "public read sections" on public.page_sections;
drop policy if exists "auth manage sections" on public.page_sections;
drop policy if exists "public read settings" on public.site_settings;
drop policy if exists "auth manage settings" on public.site_settings;
drop policy if exists "public read published posts" on public.posts;
drop policy if exists "auth manage posts" on public.posts;
drop policy if exists "public read about blocks" on public.about_blocks;
drop policy if exists "auth manage about blocks" on public.about_blocks;
drop policy if exists "public create orders" on public.web_orders;
drop policy if exists "auth manage orders" on public.web_orders;
drop policy if exists "public create order items" on public.web_order_items;
drop policy if exists "auth manage order items" on public.web_order_items;

create policy "public read product" on public.product for select using (true);
create policy "auth manage product" on public.product for all to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);

create policy "public read sections" on public.page_sections for select using (is_active=true);
create policy "auth manage sections" on public.page_sections for all to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);

create policy "public read settings" on public.site_settings for select using (true);
create policy "auth manage settings" on public.site_settings for all to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);

create policy "public read published posts" on public.posts for select using (status='published');
create policy "auth manage posts" on public.posts for all to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);

create policy "public read about blocks" on public.about_blocks for select using (is_active=true);
create policy "auth manage about blocks" on public.about_blocks for all to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);

create policy "public create orders" on public.web_orders for insert to anon, authenticated with check (true);
create policy "auth manage orders" on public.web_orders for all to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);

create policy "public create order items" on public.web_order_items for insert to anon, authenticated with check (true);
create policy "auth manage order items" on public.web_order_items for all to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);

-- 6) Storage buckets
insert into storage.buckets(id,name,public) values('product-images','product-images',true)
on conflict(id) do update set public=true;
insert into storage.buckets(id,name,public) values('post-images','post-images',true)
on conflict(id) do update set public=true;
insert into storage.buckets(id,name,public) values('site-media','site-media',true)
on conflict(id) do update set public=true;

drop policy if exists "public read product images" on storage.objects;
drop policy if exists "auth upload product images" on storage.objects;
drop policy if exists "auth manage product images" on storage.objects;
drop policy if exists "auth delete product images" on storage.objects;
drop policy if exists "public read post images" on storage.objects;
drop policy if exists "auth upload post images" on storage.objects;
drop policy if exists "auth manage post images" on storage.objects;
drop policy if exists "auth delete post images" on storage.objects;
drop policy if exists "public read site media" on storage.objects;
drop policy if exists "auth upload site media" on storage.objects;
drop policy if exists "auth manage site media" on storage.objects;
drop policy if exists "auth delete site media" on storage.objects;

create policy "public read product images" on storage.objects for select using(bucket_id='product-images');
create policy "auth upload product images" on storage.objects for insert to authenticated with check(bucket_id='product-images' and auth.uid() is not null);
create policy "auth manage product images" on storage.objects for update to authenticated using(bucket_id='product-images' and auth.uid() is not null) with check(bucket_id='product-images' and auth.uid() is not null);
create policy "auth delete product images" on storage.objects for delete to authenticated using(bucket_id='product-images' and auth.uid() is not null);

create policy "public read post images" on storage.objects for select using(bucket_id='post-images');
create policy "auth upload post images" on storage.objects for insert to authenticated with check(bucket_id='post-images' and auth.uid() is not null);
create policy "auth manage post images" on storage.objects for update to authenticated using(bucket_id='post-images' and auth.uid() is not null) with check(bucket_id='post-images' and auth.uid() is not null);
create policy "auth delete post images" on storage.objects for delete to authenticated using(bucket_id='post-images' and auth.uid() is not null);

create policy "public read site media" on storage.objects for select using(bucket_id='site-media');
create policy "auth upload site media" on storage.objects for insert to authenticated with check(bucket_id='site-media' and auth.uid() is not null);
create policy "auth manage site media" on storage.objects for update to authenticated using(bucket_id='site-media' and auth.uid() is not null) with check(bucket_id='site-media' and auth.uid() is not null);
create policy "auth delete site media" on storage.objects for delete to authenticated using(bucket_id='site-media' and auth.uid() is not null);

-- 7) Khởi tạo các section mặc định
insert into public.page_sections(section_key,title,subtitle,body,image_url,button_text,button_url,sort_order)
values
('hero','Chọn điều phù hợp, sống điều mình yêu','Những lựa chọn chăm sóc sức khỏe gần gũi, rõ ràng và tử tế — để việc quan tâm đến bản thân trở thành một phần tự nhiên trong cuộc sống mỗi ngày.',null,null,'Khám phá sản phẩm','products.html',1),
('side_banner','Tinh hoa từ vùng đất Lâm Đồng','Một khoảng dành cho banner sản phẩm hoặc chiến dịch.',null,null,'Xem sản phẩm','products.html',2),
('brand_story','Một mong muốn giản dị','DON DUONG VILLAGE được tạo nên từ mong muốn mang đến những sản phẩm chăm sóc sức khỏe lành sạch, tử tế và đáng tin cậy.','Giữa bộn bề cuộc sống, đôi khi chúng ta quên mất việc chăm sóc chính mình, cho đến khi cơ thể lặng lẽ lên tiếng nhắc nhở.',null,'Tìm hiểu thêm','about.html',3),
('bottom_banner','Sức khỏe hôm nay cho những ngày mai trọn vẹn hơn',null,null,null,'Khám phá ngay','products.html',4),
('about','Từ một mong muốn giản dị',null,'DON DUONG VILLAGE giúp mỗi người chủ động chăm sóc sức khỏe bản thân theo cách dễ dàng, thiết thực và bền vững.',null,null,null,5),
('about_story','Từ một mong muốn giản dị',null,'Giữa bộn bề cuộc sống, đôi khi chúng ta quên mất việc chăm sóc chính mình, cho đến khi cơ thể lặng lẽ lên tiếng nhắc nhở. DON DUONG VILLAGE được tạo nên từ một mong muốn giản dị: mang đến những sản phẩm chăm sóc sức khỏe lành sạch, tử tế và đáng tin cậy, để việc quan tâm đến bản thân trở thành một phần gần gũi trong cuộc sống mỗi ngày. Chúng tôi không đặt sức khỏe trong những lời hứa quá lớn lao, cũng không muốn biến việc chăm sóc bản thân thành một áp lực. Mỗi sản phẩm đều được lựa chọn và chăm chút bằng sự cẩn trọng, tâm huyết và trách nhiệm – để bạn có thể an tâm khi lựa chọn cho chính mình và những người yêu thương. Bởi với DON DUONG VILLAGE, sức khỏe của những người mình thương chưa bao giờ là điều có thể làm qua loa.',null,null,null,6),
('about_mission','Sứ mệnh',null,'DON DUONG VILLAGE giúp mỗi người chủ động chăm sóc sức khỏe bản thân theo cách dễ dàng, thiết thực và bền vững. Chúng tôi cam kết mang đến những lựa chọn rõ ràng, an toàn, để việc sống khỏe không còn là điều xa xỉ mà trở thành một phần tự nhiên trong cuộc sống hàng ngày.',null,null,null,7),
('about_vision','Tầm nhìn',null,'DON DUONG VILLAGE hướng đến trở thành thương hiệu Việt được tin tưởng và lựa chọn lâu dài, dựa trên chất lượng, minh bạch và sự tử tế.',null,null,null,8)
('about_hero','Chăm sóc sức khỏe theo cách gần gũi hơn','Trang chủ / Về chúng tôi','Chúng tôi tin rằng việc quan tâm đến bản thân không cần bắt đầu từ những điều quá lớn lao, mà từ những lựa chọn phù hợp được gìn giữ mỗi ngày.','assets/images/about-vision-default.webp','DON DUONG VILLAGE',null,9),
('about_story_meta',null,'CÂU CHUYỆN THƯƠNG HIỆU','YOUR HEALTH, YOUR GREATEST WEALTH',null,null,null,10),
('about_values_intro','Những giá trị chúng tôi luôn gìn giữ','GIÁ TRỊ CỐT LÕI','Chất lượng, minh bạch và sự tử tế là nền tảng trong từng sản phẩm và cách DON DUONG VILLAGE đồng hành cùng bạn.',null,null,null,11),
('about_closing','Chăm sóc sức khỏe hôm nay, gìn giữ yêu thương ngày mai','DON DUONG VILLAGE',null,null,'Khám phá sản phẩm','products.html',12)
on conflict(section_key) do nothing;


-- 8) Khởi tạo nội dung trang Về chúng tôi
insert into public.about_blocks(block_type,title,body,image_url,sort_order,is_active)
select * from (values
('story','Từ một mong muốn giản dị',$ddv$Giữa bộn bề cuộc sống, đôi khi chúng ta quên mất việc chăm sóc chính mình, cho đến khi cơ thể lặng lẽ lên tiếng nhắc nhở.

DON DUONG VILLAGE được tạo nên từ một mong muốn giản dị: mang đến những sản phẩm chăm sóc sức khỏe lành sạch, tử tế và đáng tin cậy, để việc quan tâm đến bản thân trở thành một phần gần gũi trong cuộc sống mỗi ngày. Chúng tôi không đặt sức khỏe trong những lời hứa quá lớn lao, cũng không muốn biến việc chăm sóc bản thân thành một áp lực.

Mỗi sản phẩm đều được lựa chọn và chăm chút bằng sự cẩn trọng, tâm huyết và trách nhiệm – để bạn có thể an tâm khi lựa chọn cho chính mình và những người yêu thương. Bởi với DON DUONG VILLAGE, sức khỏe của những người mình thương chưa bao giờ là điều có thể làm qua loa.$ddv$,'assets/images/about-story-default.webp',1,true),
('mission','Sứ mệnh',$ddv$DON DUONG VILLAGE giúp mỗi người chủ động chăm sóc sức khỏe bản thân theo cách dễ dàng, thiết thực và bền vững. Chúng tôi cam kết mang đến những lựa chọn rõ ràng, an toàn, để việc sống khỏe không còn là điều xa xỉ mà trở thành một phần tự nhiên trong cuộc sống hàng ngày.$ddv$,'assets/images/about-mission-default.webp',2,true),
('vision','Tầm nhìn',$ddv$DON DUONG VILLAGE hướng đến trở thành thương hiệu Việt được tin tưởng và lựa chọn lâu dài, dựa trên chất lượng, minh bạch và sự tử tế.$ddv$,'assets/images/about-vision-default.webp',3,true),
('value','Chất lượng','Mỗi sản phẩm được lựa chọn và chăm chút bằng sự cẩn trọng, tâm huyết và trách nhiệm.',null::text,4,true),
('value','Minh bạch','Thông tin rõ ràng để mỗi người có thể chủ động lựa chọn điều phù hợp với bản thân và gia đình.',null::text,5,true),
('value','Tử tế','Không đặt sức khỏe trong những lời hứa quá lớn lao và không biến việc chăm sóc bản thân thành áp lực.',null::text,6,true)
) as v(block_type,title,body,image_url,sort_order,is_active)
where not exists (select 1 from public.about_blocks);
