-- OWNER REVIEW ONLY. Requires existing ddv_is_admin()/product lifecycle.
-- Additive migration; do not execute automatically.
begin;
create table if not exists public.product_categories (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null check(length(trim(name)) between 1 and 200),
  slug text not null unique check(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and length(slug)<=200),
  sort_order integer not null default 0,
  is_active boolean not null default true
);
alter table public.product add column if not exists category_id bigint;
alter table public.product add constraint product_category_id_fkey
  foreign key(category_id) references public.product_categories(id) on delete set null;
create index if not exists product_category_id_idx on public.product(category_id);
create index if not exists product_categories_order_idx on public.product_categories(sort_order,id);
create or replace function public.ddv_category_updated_at() returns trigger
language plpgsql set search_path=public as $$
begin new.updated_at=now();return new;end $$;
create trigger ddv_category_updated_at before update on public.product_categories
for each row execute function public.ddv_category_updated_at();
alter table public.product_categories enable row level security;
revoke all on public.product_categories from anon,authenticated;
grant select on public.product_categories to anon,authenticated;
grant insert,update,delete on public.product_categories to authenticated;
grant usage,select on sequence public.product_categories_id_seq to authenticated;
create policy "ddv read active categories" on public.product_categories
  for select to anon,authenticated using(is_active=true);
create policy "ddv admin manage categories" on public.product_categories
  for all to authenticated using(public.ddv_is_admin() is true) with check(public.ddv_is_admin() is true);
-- Fail closed for writes even if permissive policies are added later.
create policy "ddv category insert guard" on public.product_categories as restrictive
  for insert to authenticated with check(public.ddv_is_admin() is true);
create policy "ddv category update guard" on public.product_categories as restrictive
  for update to authenticated using(public.ddv_is_admin() is true) with check(public.ddv_is_admin() is true);
create policy "ddv category delete guard" on public.product_categories as restrictive
  for delete to authenticated using(public.ddv_is_admin() is true);
commit;
